### ISSUE TITLE
[SP5] Service Desk enhancements

### ISSUE THREAD

**Issue by corydbrown** [prontotools/gravityformsconnectwise#7]
As a ConnectWise user, I want to add some fields to the Service Desk section so that I can stop using the ConnectWise email connector.

**Exit Criteria:**

- [x] Lookup and option to set Type
- [x] Lookup and option to set Sub Type
- [x] Lookup and option to set Item
- [x] Add these settings under the current "Priority" one
- [x] Notify this user when complete: https://pronto.zendesk.com/agent/tickets/303271

**Notes:**

Documentation: https://developer.connectwise.com/ConnectWise/REST

Fields affected: (we already do Board so ignore that)

![uploads/dfaacd45-7fce-40ab-ba2d-7dceb29a2605/service desk enhancements.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdfaacd45-7fce-40ab-ba2d-7dceb29a2605%2Fservice+desk+enhancements.png)

**Comment by lunarduan** [comment]
@corydbrown Please double check the site lookup. So far we have this:

![uploads/ba45445b-c99e-40f9-92b5-64951bde782f/Screen Shot 2559-07-20 at 7.07.44 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fba45445b-c99e-40f9-92b5-64951bde782f%2FScreen+Shot+2559-07-20+at+7.07.44+PM.png)

**Comment by corydbrown** [comment]
@lunarduan Let's not do anything with Site. Sorry for the confusion! I've removed it from the exit criteria.

Let me know when this is in production and I can let the client who's waiting know. 

Thank you!

**Comment by corydbrown** [comment]
@zkan has this been deployed? I don't see Type, Subtype, or Item in service ticket settings: https://alex.bypronto.com/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=connectwise&id=15&fid=2

**Comment by zkan** [comment]
@corydbrown Yes, we deployed. However, I think it's because we don't update the code in WordPress.org repo and that code replaced our latest one. I will work with @oy-np tomorrow on this.

**Comment by corydbrown** [comment]
@zkan okay cool thanks let me know

**Comment by BabyThor** [comment]
@corydbrown We've deploy this feature on bypronto

**Comment by corydbrown** [comment]
@BabyThor thank you!!!!
