### ISSUE TITLE
[SP5] [ConnectWise] API Version control

### ISSUE THREAD

**Issue by oy-np** [prontotools/gravityformsconnectwise#8]
As Pronto tools, I want our plugin to have a version control to support different version of connectwise so our clients can use them even if there are on different version.

**Exit Criteria**
* [x] use `/system/info` to check clients version
* [x] Add version control to ConnectWise plugin
* [x] version 2016.3: defaultContactId -> 2016.4 or later = defaultContact [Release note](http://forums.connectwise.com/devnetwork/f/46/t/32980) (class-gf-connectwise.php:198)
* [x] version 2016.4 or higher will use system/members firstname and lastname instead of name [Release note](http://forums.connectwise.com/devnetwork/f/46/t/34215)
* [x] opportunity salesrep and activity assign to should show member name in feed setting page
* [x] Primary contact should be add to version control too (need to check apis of each version)
* [x] Primary contact should still work correctly

**NOTE**

Right now code in bypronto and on wordpress.org are different. We are having problem with fix path so we will have to do this separately or do the card #2  first.

**Comment by prontoboss** [comment]
sp 5

**Comment by oy-np** [comment]
For testing team member issue:https://ifstechnologies.bypronto.com/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=connectwise&id=11&fid=0

https://dmatechsolutions.bypronto.com/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=connectwise&id=8&nid=56d023de109e3&fid=0

**Comment by oy-np** [comment]
Note v2016.4.41124 still use defaultcontactid

**Comment by BabyThor** [comment]
@corydbrown We've deploy this card on bypronto

**Comment by corydbrown** [comment]
thank you!

**Comment by zkan** [comment]
I've just deployed again. https://fdstech.bypronto.com/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=connectwise&id=7&fid=2

@corydbrown ConnectWise on Bypronto should have the latest code (same as on WordPress.org) by now.

<img width="536" alt="screen shot 2559-08-11 at 9 22 23 am" src="https://cloud.githubusercontent.com/assets/704794/17577208/32a8ea66-5fa5-11e6-8dee-177145bec5b6.png">

**Comment by corydbrown** [comment]
@zkan thank you!
